### ISSUE TITLE
Integrate the run.py port checker with qt-wk type experiments

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#1]
Within run.py, a port checker recognizes if the preselected port 5000 for local flask server instances is already in use. If so (i.e., when another local alfred web experiment is already running), port assignment is changed to alternative ports.

Currently, this will only work for pure web experiments, as the qt-wk userinterface controller tries to load any experiments only on the standard port and probably won't load a second experiment correctly if another local instance of alfred is already runnning.

Ideally, the port checker should run before both types of experiments and this might actually already be the case in run.py. What's missing is the dynamic loading of experiments on another port in the qt-wk interface controller. We need to forward the assigned port from run.py to there.

**Comment by jobrachem** [comment]
We removed QT-WK.
