### ISSUE TITLE
Inconsistent refactoring of QuestionGroup class

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#13]
We decided to rename QuestionGroup classes to Section. However, the main class _Section_ is currently named _PageGroup_, which is confusing for users, since we have both SegmentedSection and HeadOpenSection in the framework.

_PageGroup_ should be named _Section_. As a workaround and to allow for consistent naming, users can create a custom class _Section_ derived from _PageGroup_.

**Comment by jobrachem** [comment]
This oversight is fixed now.
