### ISSUE TITLE
Inconsistent method naming for appending operations

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#14]
Appending an item to a section or to the PageController is done with a method named _append\_item_ and appending an Element to a Page is achieved by calling _add\_element_.

While I think it is important to differentiate between appending sections or pages to pagegroups and appending elements to composite pages, we should not use both terms _add_ and _append_. Since append is what we actually do, we should rename _add\_element_ to _append\_element_.

**Comment by jobrachem** [comment]
The methods are now called `append()`. The old methods still work and call `append()` now. When one of the old methods is used, a warning is printed and logged.
