### ISSUE TITLE
QT-WK Experiments print permission errors

### ISSUE THREAD

**Issue by jobrachem** [ctreffe/alfred#17]
When running a minimal qt-wk experiment, the following error is printed multiple times:

```
ERROR:permission_manager_qt.cpp(82)] Not implemented reached in ProfileAdapter::PermissionType QtWebEngineCore::toQt(content::PermissionType)Unsupported permission type: 13
```

This does not cause the experiment to abort or any data loss.
So far, I could not find the cause of the error, although I suspect that it has something to do with the page tokens that we recently implemented.

**Comment by AsadSeeker** [comment]
did you find the solution of it ?

**Comment by jobrachem** [comment]
So far, we didn't. This bug doesn't cause any noticeable problems or data loss that we know off, and currently we only work with web experiments, so it is rather low priority for us at the moment. Do you have to deal with something similar?

**Comment by AsadSeeker** [comment]
Actually i am working on PyQt 5.13 Browser Functionality and this gives me the same error you mentioned ... so i thought to ping you, might be you have solution of this ...

**Comment by jobrachem** [comment]
I'll let you know if we can solve it :-)

**Comment by jobrachem** [comment]
We removed QT-WK entirely.
