### ISSUE TITLE
Check for page loading bug in qt-wk experiments

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#2]
With alfred 0.2b5, users would sometimes experience issues with page loading in qt-wk experiments. I will ask around for a more specific description, but as far as I remember, sometimes pages would not load in the webkit browser window and we would get a warning message from the flask server. A relatively easy fix was to just F5 or right click reload the empty page and the experiment would correctly continue. 

As far as I know, there was no systematic pattern in the occurence of this glitch, but it never happened in pure web experiments. Maybe the issue is already resolved through the new webkit version we now use, but we have to keep an open eye for this type of issue un qt-wk experiments when testing.

**Comment by jobrachem** [comment]
We removed QT-WK.
