### ISSUE TITLE
No ProgressBar status between 95% and 100%

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#203]
In experiments with many pages, the progress bar seems to stop at 95%, even if the correct number of pages was configured. It will only jump to 100% at the last page.

**Comment by jobrachem** [comment]
If I am not mistaken, this is may just be a limitation of the bootstrap progress bar that we use.

**Comment by ctreffe** [comment]
Ah, I see. Maybe it would be a good idea then to show the progress on the bar only in integers, to reduce the contrast between the area in which the progress bar actually works and the area between 95 and 100. Or, maybe, we could just show increments of 5%?
