### ISSUE TITLE
al.Image: Image is not centered when png is loaded from file

### ISSUE THREAD

**Issue by slussinator** [ctreffe/alfred#216]
I am trying to load an image into my experiment. It is not shown in center and I can't figure out how to get it into the correct position. The problem does not seem to occur when loading pictures via url. Thus I cannot produce it here. I have hashed out the line of code where I try to load the picture from file. 

Thanks in advance!

```
import alfred3 as al
exp = al.Experiment()

@exp.member
class Demo(al.Section):
    name = "demo1"

    def on_exp_access(self):
        #image = al.Image(path="files/Qpic.png")
        image=al.Image(url="https://upload.wikimedia.org/wikipedia/commons/3/31/Aicp_homescreen.bitflip_glitch_art.rerender.png")
        intro = al.Page(name="intro_demo", title="demo")
        intro += al.Text("intro text")
        intro += image
        self += intro

if __name__ == "__main__":
    exp.run()

```

**Comment by ctreffe** [comment]
Just to be clear, images that are loaded from an URL are displayed centered per default, and pictures loaded from disk are bounded to the left side of the page?

**Comment by slussinator** [comment]
seems like it. I don't believe it is meant to be this way though. Also, "position = center" does not solve the problem.

**Comment by ctreffe** [comment]
You're right, the alignment of an Image element should not depend on whether it is loaded from an URL or from disk and we'll look into that. 

In the meantime, the _position_ argument should only have an effect on the alignment when used in combination with _width_ = "full" (see the [documentation](https://alfredo3.psych.bio.uni-goettingen.de/docs/generated/alfred3.element.display.Image.html) on this) so you might want to try again with this additional argument. The _position_ argument might just work for you, after all.

**Comment by slussinator** [comment]
adding width and position does not have an effect

**Comment by ctreffe** [comment]
Okay, this issue might be similar to #213 and we will try to fix both issues in the next version.

**Comment by jobrachem** [comment]
The argument _position_ should only have an effect, when _width_ is **not** _full_, as is stated in the documentation. I would expect the _align_ argument to be the one that controls whether content within an element is displayed centered.

That said, it's of course still odd that images loaded from urls and from files are displayed differently. We'll have to look into that.

**Comment by ctreffe** [comment]
Ah, my bad... 😄

@jobrachem is right, of course.

**Comment by slussinator** [comment]
align = "center solved the problem! Thanks :D

**Comment by jobrachem** [comment]
I tested the issue in Safari, Chrome and Firefox, and cannot replicate different alignment for images loaded from URLs or from the file system. Both are left aligned by default, as stated in the docs.
