### ISSUE TITLE
Missing dependency for the template-command

### ISSUE THREAD

**Issue by jbengelsdorf** [ctreffe/alfred#223]
When the command `alfred3 terminal` is executed in the terminal, the error `ModuleNotFoundError: No module named 'mongomock'` is printed. 
After successful installation of the `mongomock`-package via `pip install mongomock`, the template command can be executed in the terminal without errors.

**Comment by jobrachem** [comment]
Thanks a lot! `mongomock` is a development dependency used for testing. I added a commit that should resolve the issue. It will be included in the next release.
