### ISSUE TITLE
Unintended bold vertical lines in al.SubmittingBar

### ISSUE THREAD

**Issue by slussinator** [ctreffe/alfred#237]
Dear Team,

I would like to use the al.SubmittingBar element with 11 points. For some reason, as can be seen in the attached file, there is a thicker line between choice points 6 and 7. Is there a way to get rid of this?

Thank you!

![image](https://user-images.githubusercontent.com/91884644/235158800-72da1d7a-91fa-4ac0-bde5-bb8d3b5c4b89.png)

**Comment by jobrachem** [comment]
Does the problem persist over multiple browsers? And does it persist when you zoom in and out? If both questions are answered yes, could you provide a link to a 1-page minimal example experiment with the problem for further investigation?

Also, does the problem occur only with 11-point scales?
