### ISSUE TITLE
helpmates read_csv_data issue and improvement request

### ISSUE THREAD

**Issue by kangaroo07** [ctreffe/alfred#47]
The read_csv function lacks one line of code which erases the first line of the data ( 'out.pop(0)' ). Since most of the csv data contain a header in the first line, it needs to be deleted. Otherwise the header will be mistaken for real data. 

Additionally it would be great if future read_csv_functions could read in data in a way that allows selecting columns by the header name. E.g. stimuli[1][1] could be stimuli[1]["name of column"]. That would increase the readability of the code and would allow to edit the csv-File without correcting the column numbers. 

Thanks and best regards

**Comment by jobrachem** [comment]
Sounds good to me!

**Comment by jobrachem** [comment]
In alfred3 v2.0, the experiment has received two new methods for iterating over csv files:

- `alfred3.experiment.ExperimentSession.read_csv_todict()`
- `alfred3.experiment.ExperimentSession.read_csv_tolist()`

Both are generators, intended for iteration. For usage see: 
- https://jobrachem.github.io/alfred_docs/html/generated/alfred3.experiment.ExperimentSession.read_csv_todict.html
- https://jobrachem.github.io/alfred_docs/html/generated/alfred3.experiment.ExperimentSession.read_csv_tolist.html
