### ISSUE TITLE
DataManager: rename add_additional_data() to set_additional_data()

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#49]
Currently, the name of our method *add_additional_data()* within the DataManager class suggests that data can only be added, but this method can also be used to update existing objects within the additional_data dictionary. Since we often need to update existing data instead of adding new data, I think we should rename this method. Therefore, I propose renaming *add_additional_data()* to *set_additional_data()*. We should keep *add_additional_data()* but with a deprecation warning.

**Comment by jobrachem** [comment]
See #51
