### ISSUE TITLE
LikertMatrix: Failed to find bundle for accelerator bundle

### ISSUE THREAD

**Issue by jobrachem** [ctreffe/alfred#5]
When moving to a page that contains a LikertMatrix or one of the elements that inherit from it (LikertElement, SingleChoiceElement, MultipleChoiceElement), the following error occurs:

`QtWebEngineProcess[41014:960846] +[MTLIOAccelDevice registerAcceleratorService:]: Failed to find bundle for accelerator bundle named: AppleIntelKBLGraphicsMTLDriver errno: 1`

The error occurs with an empty LikertMatrix (no arguments passed, using only the defaults) the same with a filled one. The experiment can be continued as usual and data is saved correctly.

**Comment by ctreffe** [comment]
This does not seem to be an error within the alfred framework but within the local server instance. The error message seems to refer to an integrated graphics card driver on your MacBook. First of all, we should check whether the error occurs on other systems.

**Comment by jobrachem** [comment]
In alfred3, the LikertMatrix was removed. One add multiple SingleChoice elements now instead.
