### ISSUE TITLE
Add a property "status" to the Experiment class

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#50]
In a variety of contexts, we use a status indicator to coordinate interactive components or to control ongoing experimental sessions. Currently, the default method is to add status variables to the additional_data dictionary, but the status of an ongoing session could (and should) be a property of the Experiment class itself. This would allow users to set and update the status of an ongoing session quick and easy.

**Comment by jobrachem** [comment]
Maybe "session_status", for the greater specificity?

**Comment by jobrachem** [comment]
In alfred3 v2.0, `alfred3.experiment.ExperimentSession.session_status` is available.
