### ISSUE TITLE
Add method set_additional_data() to the Experiment class

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#51]
Currently, users who wish to add data to the *additional_data* dictionary have to go through the experiment's data_manager and access *add_aditional_data()*. It would be much easier to work with additional data if we provided a method to access the dictionary directly from the Experiment object. Therefore, I propose that we add a new method *set_additional_data()* which links to the method within the DataManager class (see issue #49 regarding the proposed name of the new method).

**Comment by ctreffe** [comment]
Also, we should add a *get_additional_data()* method to the Experiment class. This would be a shortcut to *find_experiment_data_by_uid()* from the DataManager class.

**Comment by jobrachem** [comment]
In alfred3 v2.0, the additional data dictionary is available through:

- `alfred3.experiment.ExperimentSession.additional_data`
- `alfred3.experiment.ExperimentSession.adata` (shortcut)

It can be used just like any normal dictionary, using square-bracket syntax for accessing and setting values.
