### ISSUE TITLE
New Hooks: on_entering_section and _on_leaving_section

### ISSUE THREAD

**Issue by jobrachem** [ctreffe/alfred#9]

**Comment by ctreffe** [comment]
I propose we call these methods *on_entering* and *on_leaving*, as this would align well with our page hooks (on_showing, on_hiding).

**Comment by jobrachem** [comment]
The hooks are now called `alfred3.section.Section.on_enter` and `alfred3.section.Section.on_leave`. More here: https://jobrachem.github.io/alfred_docs/html/howto_hooks.html
