### ISSUE TITLE
Change default width for Text 

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#91]
Currently, the default _width_ of an alfred3 _Text_ element is smaller than for other elements. While this ensures good readability on various screen sizes, it causes layout inconsistencies when combining _Text_ and other elements.

To increase the consistency of element layouts, I suggest that we change the default width of _Text_ elements to match the default width of the other elements which should be the full bootstrap width (12 columns).

**Comment by jobrachem** [comment]
Included in release v2.1.5
